### ISSUE TITLE
you want to use not $NAME be package.json because it does not take /

### ISSUE THREAD

**Issue by cordoval** [ryanramage/docker-build-run-push#2]
to support username/package

**Comment by ryanramage** [comment]
to be clear you are referring to [scoped packages](https://docs.npmjs.com/misc/scope)? 

If that is the case, do you think it would be ok to make it

```
NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
```

**Comment by cordoval** [comment]
hmm but the name cannot have / so that is why we need to use another parameter

**Comment by ryanramage** [comment]
Lets assume in `package.json` the name is `@cordoval/supermodule`

with the code

```
NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
```

The `NAME` would end up being `supermodule` so there is no / in the name. I think this is what you would like, correct?

**Comment by cordoval** [comment]
no, when the package.json has a name with / it gives an error when you try npm install. just try it.

**Comment by ryanramage** [comment]
Right. Sorry, so you dont appear to be referring to scoped npm packages. Are you referring to pushing to the public docker hub like `docker push yourname/newimage` and you want to append yourname to the front of the package?

**Comment by cordoval** [comment]
yes i can do that with tagging but what for, the image should be created once with the right name

**Comment by ryanramage** [comment]
I am not fully understanding what you are looking for. If you can provide an example of the following
1. The package.json .name you want to use
2. The docker image name you are trying to achieve. 
3. If you are trying to add a username to the docker image push

**Comment by cordoval** [comment]
```
{
  "name": "cordoval/crap",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
   ...
    "webpack": "^1.12.9",
    "docker-build-run-push": "^1.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docker-build": "rm -rf node_modules && npm i --production && ./node_modules/docker-build-run-push/docker-build",
    "docker-run": "./node_modules/docker-build-run-push/docker-run",
    "docker-push": "rm -rf node_modules && npm i && make build && npm prune && ./node_modules/docker-build-run-push/docker-push"
  },
  "author": "",
  "license": "ISC"
}
```

dockerimage name cordoval/crap

the username is cordoval, so docker push cordoval/crap works and does not get rejected

**Comment by ryanramage** [comment]
Thanks! That helps a lot. And you should be more optimistic with your package names ;)

This package was originally written for private repos, but I see no reason not to support the public docker hub. 

Here is a 'hack' that might work for you:

```
{
  "docker-registry": "cordoval",
  "name": "crap",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
   ...
    "webpack": "^1.12.9",
    "docker-build-run-push": "^1.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docker-build": "rm -rf node_modules && npm i --production && ./node_modules/docker-build-run-push/docker-build",
    "docker-run": "./node_modules/docker-build-run-push/docker-run",
    "docker-push": "rm -rf node_modules && npm i && make build && npm prune && ./node_modules/docker-build-run-push/docker-push"
  },
  "author": "",
  "license": "ISC"
```

**Comment by ryanramage** [comment]
Ok @cordoval I have changed the semantics slightly when pushing to the public docker hub. Try this in your package.json

```
{
  "docker-user": "cordoval",
  "name": "crap",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
   ...
    "webpack": "^1.12.9",
    "docker-build-run-push": "^1.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docker-build": "rm -rf node_modules && npm i --production && ./node_modules/docker-build-run-push/docker-build",
    "docker-run": "./node_modules/docker-build-run-push/docker-run",
    "docker-push": "rm -rf node_modules && npm i && make build && npm prune && ./node_modules/docker-build-run-push/docker-push"
  },
  "author": "",
  "license": "ISC"
```

**Comment by cordoval** [comment]
thanks man!
