### ISSUE TITLE
Remove build logic from docker-push command; introduce docker-publish

### ISSUE THREAD

**Issue by arikon** [ryanramage/docker-build-run-push#8]
What do you think of:
- removing `docker build` logic from `docker-push`, so it will only push images to the registry
- introducing new command `docker-publish` that will do `docker-build "$*" && docker-push`

?

**Comment by arikon** [comment]
@ryanramage What do you think of this idea?

**Comment by arikon** [comment]
@ryanramage Polite ping ;)

**Comment by ryanramage** [comment]
Yes, I think this is a good idea. I will make the change.

**Comment by ryanramage** [comment]
I have removed docker-push building the image again. I have chosen not to add a docker-publish command, as the end users can do that right in there npm scripts section (npm run docker-build && npm run docker-push). 

I like the idea now that the image that one tests after build and run cant change. Great idea!

Let me know if you have any issues.

**Comment by ryanramage** [comment]
Published in 4.0.0. in commit https://github.com/ryanramage/docker-build-run-push/commit/c3546c2301d30bbb3f1621681a9bd3c38804d746

**Comment by arikon** [comment]
@ryanramage Thanks!
